url: http://cscott.github.com/mozbugs/
title: Mozilla Bugs
description: Demonstrates various bugs found in Mozilla products, for easy reference in the bugzilla tracker.
author: C. Scott Ananian
email: cscott@cscott.net
